tests: free up GPU memory
DiamondLightSource/httomolibgpu pull request #52
Opened 2023-02-02 14:11 UTC by namannimmo10

2023-02-02 15:17 UTC, team-gpu requested changes
Just a note: The `ensure_clean_memory` fixture clears everything allocated with cupy on host (pinned) and device. That's fine if everything is functional and not global data is used (which I believe is good practice anyway). Otherwise there will be dangling references.

2023-02-02 15:17 UTC, team-gpu commented on tests/test_pipeline.py
> +    data = flats = darks = data_normalize_cupy = corrected_data = None
This is not needed - the fixture is setup now that it runs before the test starts (not after), and those references are gone there anyway. 

If you would like it to cleanup at the end as well, you can modify the `ensure_clean_memory` fixture as:

```python
def ensure_clean_memory():
    cp.get_default_memory_pool().free_all_blocks()
    cp.get_default_pinned_memory_pool().free_all_blocks()
    yield None
    cp.get_default_memory_pool().free_all_blocks()
    cp.get_default_pinned_memory_pool().free_all_blocks()
```

This makes sure that it frees everything before *and* after each test that uses the fixture.

2023-02-02 15:17 UTC, team-gpu commented on tests/test_prep/test_alignment.py
> +    im = None #: free up GPU memory
no need - fixture runs after test function is finished, which will have those references removed anyway at that point.

2023-02-02 15:17 UTC, team-gpu commented on tests/test_prep/test_normalize.py
> +def test_normalize_1D_raises(data, flats, darks, ensure_clean_memory):
also not needed, since `data`, `flats`, `darks` are fixtures that depend on that one already. Check out `dark` in  `conftest.py`.

Any time a GPU data fixture is used, the clean memory is already part of the fixtures implicitly.

2023-02-02 17:48 UTC, namannimmo10 commented on tests/test_pipeline.py
> +    data = flats = darks = data_normalize_cupy = corrected_data = None
Please read this answer by the `cupy` dev lead: https://stackoverflow.com/a/53537298

2023-02-02 22:46 UTC, lotzej commented on tests/test_pipeline.py
> +    data = flats = darks = data_normalize_cupy = corrected_data = None
I understand that. But the fixture executes the memory cleanup *after* the function returns, which means the local variables will already be out of scope and their reference count dropped to zero already before the pool is cleaned. That's why it's not necessary when using a fixture.

2023-02-03 10:50 UTC, namannimmo10 commented on tests/test_pipeline.py
> +    data = flats = darks = data_normalize_cupy = corrected_data = None
good catch, thanks - I didn't look at this carefully.

2023-02-03 10:54 UTC, merged