Add fresnel filter for the pipeline
DiamondLightSource/httomolibgpu pull request #6
Opened 2022-12-06 14:31 UTC by namannimmo10

2022-12-06 14:33 UTC, namannimmo10 commented on examples/fresnel-filter.py
> +) = standard_tomo(in_file, data_key, image_key, DIMENSION, PREVIEW, PAD, comm)
```suggestion
host_data = \
    standard_tomo(in_file, data_key, image_key, DIMENSION, PREVIEW, PAD, comm)[0]
```

2022-12-06 14:39 UTC, namannimmo10 commented on src/httomolib/filtering.py
> +        Apply negative log function to data being filtering.
```suggestion
        Apply negative log function to data being filtered.
```

2022-12-06 14:43 UTC, namannimmo10 commented on src/httomolib/filtering.py
> +        ncol if ncol < padded_width - pad_width else padded_width - pad_width
```suggestion
    res_width = min(ncol, padded_width - pad_width)
```

2022-12-06 14:43 UTC, namannimmo10 commented on src/httomolib/filtering.py
> +        nrow if nrow < padded_height - pad_width else padded_height - pad_width
```suggestion
    res_height = min(nrow, padded_height - pad_width)
```

2022-12-06 15:54 UTC, namannimmo10 commented
I applied the suggestions too, please feel free to merge if the tests pass for you. Cheers.

2022-12-07 09:29 UTC, yousefmoazzam requested changes
Unfortunately, it looks like the test for the Fresnel filter is failing on my machine for a similar reason we saw with other methods, a failed tolerance assertion:
```
========================================== FAILURES ===========================================
_____________________________________ test_fresnel_filter _____________________________________

    def test_fresnel_filter():
        in_file = 'data/tomo_standard.nxs'
        data_key = '/entry1/tomo_entry/data/data'
        image_key = '/entry1/tomo_entry/data/image_key'
        dimension = 1
        preview = [None, None, None]
        pad = 0

        host_data = \
            standard_tomo(in_file, data_key, image_key, dimension, preview, pad, comm)[0]

        data = cp.array(host_data)

        pattern = 'PROJECTION'
        ratio = 100.0
        filtered_data = fresnel_filter(data, pattern, ratio)

        for _ in range(5):
            assert_allclose(cp.mean(filtered_data), 802.1125)
            assert_allclose(cp.max(filtered_data), 1039.5293)
            assert_allclose(cp.min(filtered_data), 95.74562)

        pattern = 'SINOGRAM'
        filtered_data = fresnel_filter(data, pattern, ratio)
        for _ in range(5):
>           assert_allclose(cp.mean(filtered_data), 806.74347)

tests/test_filtering.py:36:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

actual = array(806.74335, dtype=float32), desired = 806.74347, rtol = 1e-07, atol = 0
err_msg = '', verbose = True

    def assert_allclose(actual, desired, rtol=1e-7, atol=0, err_msg='',
                        verbose=True):
        """Raises an AssertionError if objects are not equal up to desired tolerance.

        Args:
             actual(numpy.ndarray or cupy.ndarray): The actual object to check.
             desired(numpy.ndarray or cupy.ndarray): The desired, expected object.
             rtol(float): Relative tolerance.
             atol(float): Absolute tolerance.
             err_msg(str): The error message to be printed in case of failure.
             verbose(bool): If ``True``, the conflicting
                 values are appended to the error message.

        .. seealso:: :func:`numpy.testing.assert_allclose`

        """  # NOQA
>       numpy.testing.assert_allclose(
            cupy.asnumpy(actual), cupy.asnumpy(desired),
            rtol=rtol, atol=atol, err_msg=err_msg, verbose=verbose)
E       AssertionError:
E       Not equal to tolerance rtol=1e-07, atol=0
E
E       Mismatched elements: 1 / 1 (100%)
E       Max absolute difference: 0.00012283
E       Max relative difference: 1.52256617e-07
E        x: array(806.74335, dtype=float32)
E        y: array(806.74347)

/dls/science/users/twi18192/conda-envs/httomolib/lib/python3.9/site-packages/cupy/testing/_array.py:24: AssertionError
------------------------------------ Captured stdout call -------------------------------------
The full dataset shape is (220, 128, 160)
[0] Pad values are (0, 0).
data/tomo_standard.nxs
/entry1/tomo_entry/data/data
0:180, :, :
[0] Data shape is (180, 128, 160) of type uint16
=================================== short test summary info ===================================
FAILED tests/test_filtering.py::test_fresnel_filter - AssertionError:
1 failed, 4 passed in 32.46s
```

I'm happy to make the necessary changes and add them to the PR since it's my machine that's seeing the error.

2022-12-07 09:47 UTC, yousefmoazzam commented
In the end it was just one calculation in the Fresnel filter test that was failing the tolerance assertion, let me know if that test still passes for you with the change I've made.

2022-12-07 10:33 UTC, namannimmo10 commented
Thank you for fixing the test! It works for me, too.

2022-12-07 10:36 UTC, merged