Add tests for reconstruction
DiamondLightSource/httomolibgpu pull request #61
Opened 2023-02-08 16:52 UTC by namannimmo10

2023-02-08 16:57 UTC, team-gpu requested changes

2023-02-08 16:57 UTC, team-gpu commented on tests/test_recon/test_algorithm.py
> +def test__filtersinc3D_cupy(data, ensure_clean_memory):
Do you consider `_filtersinc3D_cupy` a public function, part of the interface? The leading underscore suggests that it's private, and might change or be renamed any time. Tests shouldn't test private functions...

2023-02-08 16:57 UTC, team-gpu commented on tests/test_recon/test_algorithm.py
>      assert_allclose(np.std(recon_data_tomopy), 0.009089365, rtol=1e-07, atol=1e-8)
in order to ensure the shifting etc is done correctly, I'd also add 1 or 2 elements somewhere off center and verify those - or the mean along an off-centre axis or something like that. Otherwise if the whole array came back shifted (e.g. mistake in an fftshift), your test would still pass.

2023-02-08 17:01 UTC, team-gpu commented on tests/test_recon/test_algorithm.py
> +    recon_data_tomopy = reconstruct_tomopy(data, angles, 79.5, algorithm="FBP_CUDA")
I believe it's `FBP3D_device` - from the code it looks like it supports `FBP3D_host` and `FBP3D_device`

2023-02-08 17:02 UTC, team-gpu commented on tests/test_recon/test_algorithm.py
> +    recon_data_tomopy = reconstruct_tomopy(data, angles, 79.5, algorithm="FBP_CUDA")
And if you set it to `FBP3D_device`, you should get back a cupy array.

2023-02-08 17:02 UTC, namannimmo10 commented on tests/test_recon/test_algorithm.py
> +def test__filtersinc3D_cupy(data, ensure_clean_memory):
How do you suggest we test this function then? :)

2023-02-08 17:05 UTC, team-gpu commented on tests/test_recon/test_algorithm.py
> +def test__filtersinc3D_cupy(data, ensure_clean_memory):
it's tested with the `FBD_device` test

2023-02-08 17:09 UTC, team-gpu commented on tests/test_recon/test_algorithm.py
> +    recon_data_tomopy = reconstruct_tomopy(data, angles, 79.5, algorithm="FBP_CUDA")
sorry - I got confused with the naming. I mean we need a test which calls `reconstruct_tomobar` and `algorithm='FBP3D_device'`. That's missing. (this test is calling `reconstruct_tomopy`, so ignore my comments above...)

2023-02-08 17:16 UTC, namannimmo10 commented on tests/test_recon/test_algorithm.py
> +    assert recon_data.dtype == np.float32
> I mean we need a test which calls `reconstruct_tomobar` and `algorithm='FBP3D_device'`. That's missing.

It is right here, innit?

2023-02-08 17:45 UTC, team-gpu commented on tests/test_recon/test_algorithm.py
> +    assert recon_data.dtype == np.float32
I must be dreaming... it is indeed. Sorry for all that.

2023-02-08 17:48 UTC, namannimmo10 commented
@dkazanc -- `FBP_CUDA` in


is not a valid algorithm in https://github.com/tomopy/tomopy/blob/c236a2969074f5fc70189fb5545f0a165924f916/source/tomopy/recon/algorithm.py#L129... any reason why you added that?

2023-02-08 17:50 UTC, namannimmo10 commented on tests/test_recon/test_algorithm.py
> +    assert recon_data.dtype == np.float32
No worries!

2023-02-08 17:54 UTC, namannimmo10 commented on tests/test_recon/test_algorithm.py
> +def test__filtersinc3D_cupy(data, ensure_clean_memory):
I added this to be completely sure that we get the right output, but fine, I can remove this test. Thanks.

2023-02-09 10:47 UTC, dkazanc commented
_FBP_CUDA_ method it is ASTRA related thing in TomoPy https://tomopy.readthedocs.io/en/latest/ipynb/astra.html

2023-02-09 11:04 UTC, yousefmoazzam commented
@namannimmo10 I think it's a case where the docstring of a function (in this case, TomoPy's `recon()` function) is somewhat incomplete, otherwise things become too verbose; note that the type for the `algorithm` parameter is `{str, function}`, so it at least _hints_ that it's maybe not as simple as it taking only a `str`.

The `algorithm` parameter of `tomopy.recon()` is a `str` when specifying non-Astra algorithms I think.

However, I think one can also pass the `tomopy.astra` module (ie, `algorithm=tomopy.astra`) as is done in the `reconstruct_tomopy()` function in httomo. This is to then specify different algorithms that run on GPU that have been implemented in Astra, by using the `options` keyword arg, as shown in the link that Daniil posted.

The `FPB_CUDA` that you mentioned is then specifying the algorithm that will end up in the `options` dict.

2023-02-09 14:04 UTC, namannimmo10 commented
I see, thanks Yousef and Daniil... I am not touching `reconstruct_tomopy` in this PR although it can be improved.

2023-02-09 15:27 UTC, namannimmo10 commented
I think this should be fine to complete #60! Let's add more tests in subsequent PRs.

2023-02-09 15:37 UTC, merged